
server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route     #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service      #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service      #匹配后提供服务的路由地址
          predicates:                    # 断言
            - Path=/payment/lb/**        # 路径相匹配的进行路由
            #- After=2021-12-13T14:58:37.485+08:00[Asia/Shanghai]  # 到这个时间之后才能执行（还可以用Before（之前）、Between（之间））
            #- Cookie=username,zzyy      # 命令行中启动curl http://localhost:9527/payment/lb --cookie "username=zzyy"
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式（curl http://localhost:9527/payment/lb -H "X-Request-Id:123"）
            #- Host=**.atguigu.com       # 通过参数中的主机名作为匹配规则 (curl http://localhost:9527/payment/lb -H "host: www.atguigu.com")
            #- Method=GET
            #- Query=username, \d+       #要有参数名并且值还是整数才能路由（http://localhost:9527/payment/lb?username=1）

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


